services:
  server:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://192.168.0.114:27017/recovery
    ports:
      - "8080:8080"
